[package]
name = "derive"
version = "0.1.0"
authors = ["FenQiDian <email@fenqi.moe>"]
edition = "2018"
resolver = "2"

[lib]
proc-macro = true

[dependencies]
darling = "0.13.0"
proc-macro2 = "1.0.26"
quote = "1.0.9"
syn = { version = "1.0.72", features = ["full"] }
